image: 'Visual Studio 2017'
version: '{build}'

environment:
   QTDIR: C:\Qt\5.12\msvc2017_64

#clone_folder: c:\build\snomcontrol

before_build:
  - set PATH=%QTDIR%\bin;%PATH%

build_script:
  - mkdir build
  - cd build
  - cmake -G"Visual Studio 15 2017 Win64" -DCMAKE_BUILD_TYPE=Release -DCMAKE_PREFIX_PATH=%QTDIR% ..
  - cmake --build . --target install
