
stages:
- build


variables:
  GIT_SSL_NO_VERIFY: "true"


before_script:
   - mkdir -p ~/.ssh
   - echo "$SERVER_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_ed25519
   - chmod 600 ~/.ssh/id_ed25519
   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
   - git config --global http.sslVerify false
   - sudo apt-get -qq update && sudo apt-get install -qq -y cmake fuse wget


.build_template: &build_linux
   stage: build
   script:
      - scripts/build.sh
   artifacts:
      paths:
         - "*.AppImage"
      expire_in: 1 week


build:qt5.9-linux:
  image: a12e/docker-qt:5.9-gcc_64
  <<: *build_linux

  #build:qt5.12-linux:
  #  image: a12e/docker-qt:5.12-gcc_64
  #  <<: *build_def
